<div id="cko-payment-container">
    <div id="cko-form-holder" data-mage-init='{"loader": {}}'>
        <form class="widget-container" id="embeddedForm" method="POST" action="<?= $block->getUrl($block->tools->modmeta['tag'] . '/payment/placeorderajax'); ?>"></form>
    </div>

    <?php if (!$block->isAutoCapture()): ?>
        <button id="cko-send-card" type="button" class="action primary"  title="<?= $block->escapeHtmlAttr(__('Authorize')) ?>">
            <?= $block->escapeHtml(__('Authorize')) ?>
        </button>
    <?php else: ?>
        <button id="cko-send-card" type="button" class="action primary"  title="<?= $block->escapeHtmlAttr(__('Capture')) ?>">
            <?= $block->escapeHtml(__('Capture')) ?>
        </button>
    <?php endif; ?>

    <div class="loading-mask" data-role="loader">
        <div class="loader">
            <img src="<?= $block->getViewFileUrl('images/loader-1.gif'); ?>">
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'mage/url', 'domReady!', 'framesjs'], function ($, Url) {
        // Start the loader
        //$('.loading-mask').show();

        // Prepare the elements
        var buttonId = '#cko-send-card';
        var ckoContainerSelectorId = '#cko-form-holder';
        var ckoPublicKey = '<?= $block->config->getPublicKey(); ?>';
        var paymentForm = document.getElementById('embeddedForm');
        var ckoTheme = '';
        var ckoDebugMode = false;

        // Initialize the embedded form
        Frames.init({
            publicKey: ckoPublicKey,
            containerSelector: ckoContainerSelectorId,
            theme: ckoTheme,
            debugMode: ckoDebugMode,
            frameActivated: function () {
                $(buttonId).attr("disabled", true);
            },
            cardSubmitted: function() {
                $(buttonId).attr("disabled", true);
            },
            cardValidationChanged: function(event) {
                $(buttonId).attr("disabled", !Frames.isCardValid());
            },
            cardTokenised: function(event) {  
                // Send the request
                ajaxRequest = $.ajax({
                    url: '<?= $block->getUrl('checkout_com/payment/placeorderajax'); ?>',
                    type: "post",
                    data: {
                        form_key: window.FORM_KEY,
                        "cko-card-token": event.data.cardToken
                    }
                });                
                
                // Callback handler on success
                ajaxRequest.done(function (response, textStatus, jqXHR) {
                    if (response.error) alert(response.message);
                    console.log(response);
                });

                // Callback handler on failure
                ajaxRequest.fail(function (jqXHR, textStatus, errorThrown) {
                    // Todo - improve error handling
                });

                // Callback handler always
                ajaxRequest.always(function () {

                });

                // Add the card token to the form
                //Frames.addCardToken(paymentForm, event.data.cardToken);

                // Submit the payment form
                //paymentForm.submit();
            },
        });  

        // Handle the submit event
        $(buttonId).on('click touch', function (event) {
            //$('.loading-mask').show();
            event.preventDefault();
            Frames.submitCard();
        });

        // Handle the payment option click event
        var eventSource = $('#order-billing_method_form input[type="radio"]');
        var eventTarget = $('#p_method_checkout_com_admin');
        var targetWidget = $('#cko-payment-container');
        (eventTarget.is(':checked')) ? targetWidget.show() : targetWidget.hide();
        eventSource.on('click touch', function (event) {
            if (eventTarget.is(':checked')) {
                targetWidget.show();
            }
            else {
                targetWidget.hide();
            }
        });

        // Stop the loader
        $('.loading-mask').hide();
    });
</script>